---
title: "Thalas "
author: "W. Kaisers"
date: "07.01.2022"
output:
    html_document:
        theme: default
        toc: true
        toc_depth: 3
        number_sections: true
---


--------------------------------------------------------------------------------

<!-- ----------------------------------------------------------------------- -->
# Data definition
<!-- ----------------------------------------------------------------------- -->


## Basic entities

 - A **device** is a data-capturing computer delivering measured values via 
   *REST*-api. A device is identified by a name and an IP-address or a MAC
   address. 
   Devices carry location identifiers which may change over time.
 - A **location** denotes an outlined physical position of a device recording.
   It can be a room inside a building (with only one device) or a defined
   place within a room containing multiple devices (for example a PACU).
 - A **patient** is a person, represented by a medical record, on which 
   device captured measurements are acquired.
   

## Interaction level entities

 - A **connection** is a period of successful network communication between an
   interface (for example a *thalas* server) and a *device*.
   during the time of a connection, the server and the device can communicate
   with each other.
   By specifying the *End-Time*, a connection expires.
   Connections also manage Xenon RS232 interface status.
 - A **RecordingSite** represents a device which is placed in a location.
   In practice, this may mean for example, that a ventilator together with
   a Xenon-device is inside a defined room.
 - A **PatientAssociation** links a patient and a *RecordingSite*.
   For the time of this association, all related recordings can be assigned to
   the respective patient.
    

The entities in this level are subject to human interaction.
Placing devices and patients in a location as well as booting of devices will
be done manually.
Thus, human input is required for correct establishing of associations.


## Recordings

Recordings emerge from data transfer from one or more Xenon clients to a thalas
server.
By itself, these recordings solely solely reflect an established communication
with a device.
Further meaningful utilization bases on association with a patient and this is
usually done using locations.

 - An **episode** is a series of uninterrupted observations captured by a
  single device on a single patient in a single location.

These definitions shall facilitate the association of captured recordings to
an electronic medical record. Therefore:

 - A location should be specified in a way allowing a 1:1 relation to an episode.
   A criterion could be the existence of wall connections to which a device
   needs to be connected.

    
The connections of data capturing servers to recording devices are fragile:
 - A recording may be terminated by the device because a patient is
   disconnected or a device has been turned off or 
 - the network connection between server and device is lost.
   
 - A **recording** is the entirety of observations captured by a single
    device during a single *connection*. It has been recorded in a single 
    location. There may be changes of patients during a single recording.
 - A **session** is a part of an episode which is observed on a single
    therapeutic session (on a single patient).
 - A **period** is a part of a session included in a single report.


## Observations

  - An **observation** is the measured value of a single parameter at a single
    time point
  - A **parameter** is the output of a specified measurement procedure 
      as a surrogate for a defined entity for example *tidal volume* or
      *F<sub>i</sub>O<sub>2</sub>*. Parameters are represented by unique ID's
      for example [Snomed CT](https://www.snomed.org/)
    


--------------------------------------------------------------------------------

<!-- ----------------------------------------------------------------------- -->
# MySql
<!-- ----------------------------------------------------------------------- -->


## Create database

 - Open admin terminal `sudo su`
 - Login `mysql -u root`
 - Display port: `SHOW GLOBAL VARIABLES LIKE 'PORT';`
 
## Logging

 - Enable Access denied logging: `SET GLOBAL log_warnings=2;`
 - `SHOW GLOBAL VARIABLES LIKE 'log_error';`
 - [Error logs](https://mariadb.com/kb/en/server-system-variables/#log_error)
 - [General query log](https://mariadb.com/kb/en/general-query-log/)
 - `SET GLOBAL general_log_file='/var/log/mysql/mariadb.log';`
 - `SET GLOBAL log_output = 'FILE';`
 - `SET GLOBAL general_log = 'ON';`
 - `SHOW VARIABLES LIKE 'general_log%';`
 
## SSL

 - `SHOW VARIABLES LIKE '%ssl%';`
 - `have_ssl` is `DISABLED`
 - SET GLOBAL have_ssl = 'YES';

Create thalas database:
```c
CREATE DATABASE thalas;
CREATE USER 'thalasroot'@'localhost' IDENTIFIED BY 'xyz';
GRANT ALL ON thalas.* TO 'thalasroot'@'localhost';
```

Change password: 
```c
SET PASSWORD FOR 'thalasroot'@'localhost' = PASSWORD('xxz');
```

## Backup and restore

 - Backup `mysqldump thalas > thalas.sql`
 - Replace `sed -i 's/utf8mb4_0900_ai_ci/utf8mb4_general_ci/g' thalas.sql`
 - Restore `mysql thalas < thalas.sql`

The replace step resolves the *Unknown collation issue*.
It replaces 'utf8mb4_0900_ai_ci' with 'utf8mb4_general_ci'.

### Find and replace with sed:

 - Syntax `sed -i 's/SEARCH_REGEX/REPLACEMENT/g' input-file.txt`
 - The option `-i` tells *sed* to change file in place (instead of writing to standard output)
 - The flag `s` is the substitute command
 - The flag `g` adopts general substitution (not only the first occurrence in a line is replaced)

### Add Column

 - `ALTER TABLE episode ADD COLUMN deviceid BIGINT;`
 - `ALTER TABLE device ADD COLUMN port INTEGER;`
 - `UPDATE device SET port = 4000;`

--------------------------------------------------------------------------------

<!-- ----------------------------------------------------------------------- -->
# Episodes
<!-- ----------------------------------------------------------------------- -->

A thalas-epiode is defined as a series of xenon queries, done on a single
xenon-episode.


--------------------------------------------------------------------------------

<!-- ----------------------------------------------------------------------- -->
# Snomed CT
<!-- ----------------------------------------------------------------------- -->
´

[Snomed](https://confluence.ihtsdotools.org):

 - A *Snomed CT identifier* is a unique integer, applied to components
 - [Dräger](https://www.draeger.com/Library/Content/Beatmungsmodi_in_der_Intensivmedizin_nomenklatur-bk-9066354-de.pdf)
 
## Anesthesia related identifier

 - Anesthesia CRG
 
 - [Snomed-CT via Bioontology](https://bioportal.bioontology.org/ontologies/SNOMEDCT)
 - [EBI homepage](https://www.ebi.ac.uk/ols/ontologies/snomed)


+---------------+---------------+---------------------------------------------------------+
|               | Snomed CT ID  | Description                                             |
+:==============+:==============+:========================================================+
|               | 371907003     | Oxygen administration by nasal cannula                  |
+---------------+---------------+---------------------------------------------------------+
|               | 243142003     | Dual pressure spontaneous ventilation support           |
+---------------+---------------+---------------------------------------------------------+
|               | 250854009     | Positive end expiratory pressure                        |
+---------------+---------------+---------------------------------------------------------+
|               | 286812008     | Pressure controlled ventilation                         |
+---------------+---------------+---------------------------------------------------------+
 
--------------------------------------------------------------------------------

<!-- ----------------------------------------------------------------------- -->
# Chart.js
<!-- ----------------------------------------------------------------------- -->

## Installation

 - `npm i date-fns chart.js chartjs-adapter-date-fns`



--------------------------------------------------------------------------------

<!-- ----------------------------------------------------------------------- -->
# Angular
<!-- ----------------------------------------------------------------------- -->

The Angular frontend development environment is located in `ngThalas` project.
For development purposes, server requests are redirected to `thalas` using
the `proxy-config` mechanism.

 - Requests to `/data/*` are redirected to `localhost:4040`
 - the `npm start` script starts angular serving using the `proxy.config.json` file

